### PR TITLE
Upgrade google cast

### PR DESCRIPTION
**Pull request by charliesbox**
- Fixed an issue with android. It didn't display the chromecasts around
- Clean up of default values

### CODE REVIEW

**Comment by RyderMS** [comment]
hey @charliesbox, trying to run the example off your PR on Android, but I am hitting a weird issue when running `react-native run android`:  `Android project not found. Maybe run react-native android first?`
Running `react-native android` as the prompt suggest does nothing as its not a valid command. I'll Google-fu a bit to see if this is a common issue, but let me know if you have a workaround.

**Comment by RyderMS** [comment]
after running `react-native upgrade` so  I could compile the project for Android, I get a 
**Cannot read property 'DEVICE_AVAILABLE' of undefined, which I assume is trying to grab it off 'Chromecast'. I can't seem to even set a breakpoint anywhere within main.js before this exception gets thrown :(

**Comment by charliesbox** [comment]
oh wow, seems quite weird. One more favor @RyderMS. Could you try the example from the branch stand-alone? Just to double check :)

**Comment by charliesbox** [comment]
Moving to https://github.com/charliesbox/react-native-google-cast/pull/42 as the final effort to fix the issues.

**Pull request closed without merging**
